---
title: "rMSIproc analysis"
author: "Jordi Rofes"
date: "`r Sys.Date()`"
output: html_document
---

### Preparations

```{r}

# Insert where your data is located (The peak matrix and the .tar images)
wDir <- "C:/Users/jordi/Desktop/Metabolomica/Projecte MALDI/CollCap" 

# Insert the name of the peak matrix .zip
peakData <- "/mergeddata-peaks.zip"

# Insert the group for each image (control, control, problem, ...) in order
groupsImg <- c("Control", "Control", "Transition", "Transition", "Tumor", "Tumor") 

```

### Extracting the Peak Matrix

```{r results= "hide"}

# Here we extract the Peak Matrix from the .zip and create and object with all the data assigned to peakM
peakM <- rMSIproc::LoadPeakMatrix(file.path(wDir, peakData))

```

#### Exploring the peak matrix

```{r, }

#Select m/z to plot and image number out of peakM$names to plot
peakM$names
mz2plot <- 790   #Hint# You can find the maximum mz in your data by using length(peakM$mass)
img2plot <- 2    #Hint# Writing 0 Allows you to plot all the images at the same time


a <- rMSIproc::plotPeakImageG(peakMatrix = peakM, mass = mz2plot)
b <- plotly::ggplotly(a)


## a <- rMSIproc::plotValuesImageG(peakM)

```

### Normalizations

```{r}
## Data normalization is a key step to remove part of the systematical error so the data represents more the biological variation
## There are several ways to normalize the data:
    ## TIC (Total Ion Count): 
    ## aqTIC (aquired TIC)
    ## RCS ()


```

### Medium Spectra

```{r}
#We can use rMSI functions to plot the average spectra of an image to explore the raw data
#First we have to put the path to the .tar that contains the image.
imageName <- "/CapiColl_Au_S01_1_sub-proc.tar"  #Hint# Even if your data is a .zip/.rar when you write the imageName you have to                                                     #Hint# write it as a .tar.

#Next, we run the code and a new window will appear allowing us to see the average spectra and interact with it.

image <- rMSI::LoadMsiData(file.path(wDir, imageName))
avSpec1 <- rMSIproc::AverageSpectrum(image)
rMSI::plotSpectra(mass = image$mass, intensity = avSpec1)

```

### PCA

```{r }

dataNormTic <- peakM$intensity/peakM$normalizations$TIC ### Dividim les intensitats pel factor de normalització TIC 
pca <- prcomp(dataNormTic, center = T, scale. = T) ### Fem la PCA de la matriu de pics

for (i in which(pca$sdev > 2)){
  
  rMSIproc::plotValuesImage(peakM, pca$x[,i])

}

```

### K-means

```{r warning=FALSE}

dataNormTic <- peakM$intensity/peakM$normalizations$TIC ### Dividim les intensitats pel factor de normalització TIC 

clData <- vector(mode = "list",length = length(peakM$numPixels)) 

for (i in 1:length(peakM$numPixels)){ 
 if (i == 1){
    clData[i] <- list(kmeans(dataNormTic[1:peakM$numPixels[i], ], 2))
 } else {
    clData[i] <- list(kmeans(dataNormTic[(sum(peakM$numPixels[1:(i-1)])+1):sum(peakM$numPixels[1:i]), ], 2))
 }
}

clusImages <- lapply(clData, function(x){
  return(x[1]) 
})

allClusImages <- unlist(clusImages)


rMSIproc::plotValuesImage(peakM, allClusImages)

```

### Plots PCA + K-means

```{r}


```



